name: Provisioning infrastructure and Deployment for renderer CloudRun

on: 
  push:
    branches:
      - feat-tf     
env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA }}  
  REPO_NAME: renderer
  RUN_REGION: europe-west1
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
jobs:
  setup-build-deploy-cloudrun:
    name: "Setup, Build, and Deploy CloudRun- '${{github.ref}}'"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    # Setup gcloud CLI  
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCP_SA }}  
        export_default_credentials: true
        project_id: ${{ secrets.CLOUD_RUN_PROJECT_ID }}      
    - name: Create tf state bucket    
      run: |-
        if ! gsutil ls | grep gs://${{ env.BUCKET_NAME }} ;then gsutil mb -p ${{ env.PROJECT_ID }} -l ${{ env.RUN_REGION }} -b on gs://${{ env.BUCKET_NAME }};fi   
    - name: Create cloud run sa   
      run: |-
        if ! gcloud iam service-accounts list | grep cloudrun-identity ;then gcloud iam service-accounts create cloudrun-identity;fi       
    - name: Enable docker auth
      run: |-     
        gcloud --quiet auth configure-docker      
    - name: Build and tag image
      run: |-
        docker build . --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:$GITHUB_SHA      
    - name: Push image to GCR
      run: |-
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:$GITHUB_SHA
    # Terraform remote state GCS
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform init
      id: init
      run: terraform init -backend-config="bucket=terraform1-state-renderer" -backend-config="prefix=dev"
      continue-on-error: false
      working-directory: ./tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }}
    - name: Terraform Plan
      id: plan
      run: terraform plan
      continue-on-error: false
      working-directory: ./tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }} 
    - name: Terraform apply
      id: apply
      run: |-
        terraform apply \
            -var="docker_image=gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:$GITHUB_SHA" \
            -var="service_name=renderer" \
            -var="cloudrun_sa=cloudrun-identity@nodejsapp-314207.iam.gserviceaccount.com" \
            -var="invoker_member=serviceAccount:cloudrun-identity@nodejsapp-314207.iam.gserviceaccount.com"  \
            -auto-approve 
      continue-on-error: false
      working-directory: ./tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS}}
