name: Provisioning infrastructure and Deployment for renderer CloudRun


on: 
  push:
    branches:
      - dev
      
env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
  GOOGLE_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT }}  
  REPO_NAME: renderer
  RUN_REGION: europe-west1
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
jobs:
  setup-build-deploy-cloudrun:
    name: "Setup, Build, and Deploy CloudRun- '${{github.ref}}'"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    # Setup gcloud CLI  
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}  
        export_default_credentials: true
        project_id: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
        
    - name: Create tf state bucket    
      run: |-
        if ! gsutil ls | grep gs://$BUCKET_NAME ;then gsutil mb -p $PROJECT_ID -l $RUN_REGION -b on gs://$BUCKET_NAME;fi   
        
    - name: Enable docker auth
      run: |-     
        gcloud --quiet auth configure-docker
        
    - name: Build and tag image
      run: |-
        docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA
        
    - name: Push image to GCR
      run: |-
        docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA          
  
    # Terraform remote state GCS
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1


    - name: Terraform init
      id: init
      run: terraform init
      continue-on-error: false
      working-directory: ./tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }}
    - name: Terraform Plan
      id: plan
      run: terraform plan
      continue-on-error: false
      working-directory: ./tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }}   
    - name: Terraform apply
      id: apply
      run: terraform apply -var="docker_image=gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA" -auto-approve 
      continue-on-error: false
      working-directory: ./tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS}} 
